id: P003217
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:08.794271
source_metadata:
  id: bdr:W1KG422
  title: མེས་པོའི་བྱུང་བ
  author: ''
  volumes:
    24474e13534843928c562b2191ea9c0e:
      image_group_id: I1KG425
      title: ''
      volume_number: 1
      total_pages: 386
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
