id: P003217
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG422
  title: མེས་པོའི་བྱུང་བ
  author: ''
  volumes:
    24474e13534843928c562b2191ea9c0e:
      image_group_id: I1KG425
      title: ''
      volume_number: 1
      total_pages: 386
      base_file: v001.txt
